# Generated by Django 5.0.4 on 2025-05-24 11:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Admin', max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=50)),
                ('uuid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='siteedit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, default=models.CharField(blank=True, max_length=50, null=True), max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dis', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('limited', models.BooleanField(blank=True, default=False, null=True)),
                ('kyc', models.BooleanField(blank=True, default=False, null=True)),
                ('idx', models.IntegerField(default=1)),
                ('intrest', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='allplan',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='invested',
            name='howmantime',
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='timesamp',
        ),
        migrations.AddField(
            model_name='allplan',
            name='daygiven',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='allplan',
            name='interest',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='invested',
            name='off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='databirth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='hiddekyc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userclient',
            name='pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='referamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='userclient',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='submitekyc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='withdrawincome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 7, 42, 15, 177466)),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allplan',
            name='maxplan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allplan',
            name='minplan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allplan',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allplan',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.allcoin'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 7, 42, 15, 176893)),
        ),
        migrations.RemoveField(
            model_name='invested',
            name='useronplan',
        ),
        migrations.AlterField(
            model_name='userclient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='depositincome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='howmanreferral',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='netincome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userclient',
            name='message',
            field=models.ManyToManyField(blank=True, to='app.adminmessage'),
        ),
        migrations.CreateModel(
            name='Kycuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filex', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('fathernamef', models.CharField(blank=True, max_length=50, null=True)),
                ('fathernamel', models.CharField(blank=True, max_length=50, null=True)),
                ('PAN', models.CharField(blank=True, max_length=50, null=True)),
                ('DateofBirth', models.DateField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('PANStatue', models.CharField(blank=True, max_length=50, null=True)),
                ('martialstatue', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('proofaddress', models.CharField(blank=True, max_length=50, null=True)),
                ('disableshow', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userclient')),
            ],
        ),
        migrations.AddField(
            model_name='invested',
            name='useronplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.allplan'),
        ),
    ]
