# Generated by Django 4.2.7 on 2024-02-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_siteedit_remove_invested_howmantime_allplan_daygiven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=50)),
                ('uuid', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userclient',
            name='referamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userclient',
            name='withdrawincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userclient',
            name='message',
            field=models.ManyToManyField(blank=True, to='app.adminmessage'),
        ),
    ]
