# Generated by Django 5.0.4 on 2025-05-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adminmessage_siteedit_remove_allplan_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='timesamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 24, 7, 44, 9, 929034), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 7, 44, 9, 932725)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 7, 44, 9, 931569)),
        ),
    ]
