# Generated by Django 4.2.7 on 2024-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminmessage_userclient_referamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
