# Generated by Django 4.2.7 on 2024-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adminmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
