# Generated by Django 4.2.7 on 2024-02-09 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 9, 18, 18, 37, 475654), null=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='name',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 18, 18, 37, 481658)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 18, 18, 37, 478657)),
        ),
    ]
