# Generated by Django 4.2.7 on 2024-02-10 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_adminmessage_date_alter_adminmessage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='userclient',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 10, 11, 47, 234133), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 10, 11, 47, 242144)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 10, 11, 47, 242144)),
        ),
    ]
