# Generated by Django 4.2.7 on 2024-02-15 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allplan',
            name='logo',
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 22, 53, 15, 996178), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 53, 15, 999177)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 53, 15, 998177)),
        ),
    ]
