# Generated by Django 4.2.7 on 2024-02-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteedit',
            name='locatio',
        ),
        migrations.AddField(
            model_name='siteedit',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteedit',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 16, 20, 45, 10, 458934), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 45, 10, 458934)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 45, 10, 458934)),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='limited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
