# Generated by Django 4.2.7 on 2024-02-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_siteedit_locatio_siteedit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='dis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 16, 20, 45, 52, 933954), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 45, 52, 933954)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 20, 45, 52, 933954)),
        ),
    ]
