# Generated by Django 4.2.10 on 2024-02-26 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_siteedit_dis_alter_adminmessage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteedit',
            name='kyc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 26, 12, 45, 16, 716811), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 45, 16, 718798)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 45, 16, 717994)),
        ),
    ]
