# Generated by Django 4.2.11 on 2024-03-20 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 20, 8, 2, 42, 821460), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 8, 2, 42, 823628)),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='logo',
            field=models.FileField(blank=True, max_length=6000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 8, 2, 42, 822855)),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
