# Generated by Django 4.2.5 on 2024-03-31 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 31, 17, 53, 22, 331282), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 17, 53, 22, 337370)),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 17, 53, 22, 334985)),
        ),
        migrations.AlterField(
            model_name='kycuser',
            name='filex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteedit',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
