# Generated by Django 4.2.5 on 2024-05-13 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 13, 17, 10, 10, 904846), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 17, 10, 10, 911229)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 17, 10, 10, 908756)),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='depositincome',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='netincome',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='withdrawincome',
            field=models.FloatField(default=0),
        ),
    ]
