# Generated by Django 4.2.5 on 2024-05-13 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 13, 17, 19, 16, 245578), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 17, 19, 16, 249146)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 17, 19, 16, 247766)),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='balance',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='depositincome',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='netincome',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='withdrawincome',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
