# Generated by Django 5.0.4 on 2024-05-26 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 27, 0, 43, 11, 761283), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 43, 11, 763281)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 43, 11, 762282)),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='referamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
