# Generated by Django 5.0.4 on 2024-05-26 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='referamountcash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 27, 0, 53, 49, 584894), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 53, 49, 584894)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 0, 53, 49, 584894)),
        ),
    ]
