# Generated by Django 5.0.4 on 2024-05-27 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_userclient_country_userclient_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='databirth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 27, 19, 54, 50, 532444), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 54, 50, 532444)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 54, 50, 532444)),
        ),
    ]
