# Generated by Django 5.0.4 on 2024-05-30 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_userclient_address_userclient_databirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 30, 18, 49, 42, 998470), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 18, 49, 42, 998470)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 18, 49, 42, 998470)),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
