# Generated by Django 5.0.4 on 2024-05-30 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclient',
            name='referamountcash',
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 30, 18, 58, 19, 685221), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 18, 58, 19, 685221)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 18, 58, 19, 685221)),
        ),
    ]
