# Generated by Django 5.0.4 on 2024-05-30 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_userclient_referamountcash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 30, 19, 39, 55, 99023), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 19, 39, 55, 99023)),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 19, 39, 55, 99023)),
        ),
    ]
