# Generated by Django 5.0.4 on 2024-09-07 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='hiddekyc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 7, 9, 30, 23, 223881), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 9, 30, 23, 223881)),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 9, 30, 23, 223881)),
        ),
    ]
