# Generated by Django 5.0.4 on 2024-10-01 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_adminmessage_date_alter_allcoin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 1, 11, 57, 52, 372721), null=True),
        ),
        migrations.AlterField(
            model_name='allcoin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 11, 57, 52, 373721)),
        ),
        migrations.AlterField(
            model_name='allplan',
            name='interest',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='invested',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 11, 57, 52, 373721)),
        ),
    ]
